spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          # import.sql에서 하나의 쿼리문을 여러 줄로 나눠서 써도 인식하도록 하는 설정
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
jwt:
  key: kevin12341234123412341234123412341234adsfgeeettwaeaafasfsadf
  ATExpiration: 10
  RTExpiration: 420